services:
  - type: web
    name: xx-commerce-api
    env: node
    plan: free
    buildCommand: ./deploy.sh
    startCommand: ./deploy.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://xx-commerce-client.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

  - type: web
    name: xx-commerce-client
    env: static
    plan: free
    buildCommand: |
      echo "Building client..."
      cd client
      npm install
      npm run build
      echo "Client build completed!"
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://xx-commerce-api.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
